# -*- coding: utf-8 -*-
"""perfumaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Guu1yoqXsK2BDaLodNHZscczaORlFWi4
"""

produtos = [
    {"nome": "Perfume Floral", "categoria": "Perfumes", "preco": 129.90},
    {"nome": "Colônia Masculina", "categoria": "Perfumes", "preco": 99.50},
    {"nome": "Creme Hidratante", "categoria": "Cuidados com a Pele", "preco": 45.00},
    {"nome": "Sabonete Líquido", "categoria": "Higiene", "preco": 22.30},
    {"nome": "Loção Pós-Barba", "categoria": "Barbear", "preco": 38.90},
    {"nome": "Shampoo Reconstrutor", "categoria": "Cabelos", "preco": 29.90},
    {"nome": "Condicionador", "categoria": "Cabelos", "preco": 28.50},
    {"nome": "Óleo Corporal", "categoria": "Cuidados com a Pele", "preco": 58.00},
    {"nome": "Desodorante Roll-on", "categoria": "Higiene", "preco": 14.20},
    {"nome": "Máscara Capilar", "categoria": "Cabelos", "preco": 67.80}
]

def mostrar_categorias():
    categorias = set()
    for produto in produtos:
        categorias.add(produto["categoria"])
    print("Categorias disponíveis:")
    for categoria in categorias:
        print(f"- {categoria}")

def mostrar_produtos_da_categoria(categoria_escolhida):
    encontrou = False
    print(f"\nProdutos da categoria '{categoria_escolhida}':")
    for produto in produtos:
        if produto["categoria"].lower() == categoria_escolhida.lower():
            print(f"- {produto['nome']} | Preço: R$ {produto['preco']:.2f}")
            encontrou = True
    return encontrou

def main():
    while True:
        mostrar_categorias()
        categoria = input("\nDigite o nome da categoria desejada (ou 'sair' para encerrar): ")
        if categoria.lower() == 'sair':
            print("Programa encerrado. Até logo!")
            break
        if not mostrar_produtos_da_categoria(categoria):
            print("Categoria inválida ou sem produtos. Tente novamente.")

main()